# description: collect counts in `*.ReadsPerGene.out.tab` files generated by STAR, concat them into a matrix.
# author: panyq357
# date: 2023-08-23

from pathlib import Path

import pandas as pd

star_result_dir = Path("results/star_mapping")
out_dir = Path("results/collect_star_counts")

def main():

    count_matrix = pd.DataFrame()
    for tab_path in star_result_dir.glob("*.ReadsPerGene.out.tab"):
        tab = pd.read_table(tab_path, header=None, index_col=0)
        tab = tab.iloc[4:, ]  # Remove leading 4 statistical rows.
        sample_counts = tab.iloc[:, 0]
        sample_counts.name = tab_path.name.replace(".ReadsPerGene.out.tab", "")
        count_matrix = pd.concat([count_matrix, sample_counts], axis=1)

    count_matrix = count_matrix[sorted(count_matrix.columns)]

    if not out_dir.exists():
        out_dir.mkdir()
    count_matrix.to_csv(out_dir / "counts.csv")

if __name__ == "__main__":
    main()

